In [2]:
import lightning as L
import torch
from constants import FOLDER_NAME

In [7]:
from EnvmapAffine import EnvmapAffine
class_name = EnvmapAffine


In [16]:
CKPT_PATH = "/pure/tu150/output/sd-light-time/20240703/multi_mlp_fit/lightning_logs/version_9/checkpoints/epoch=000159.ckpt"
model = class_name.load_from_checkpoint(CKPT_PATH)

Loading pipeline components...:   0%|          | 0/6 [00:00<?, ?it/s]

You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .


In [17]:
model.eval()

EnvmapAffine(
  (unet_trainable): ParameterList(
      (0): Parameter containing: [torch.float32 of size 1 (GPU 0)]
      (1): Parameter containing: [torch.float32 of size 256x8192 (GPU 0)]
      (2): Parameter containing: [torch.float32 of size 256 (GPU 0)]
      (3): Parameter containing: [torch.float32 of size 256x256 (GPU 0)]
      (4): Parameter containing: [torch.float32 of size 256 (GPU 0)]
      (5): Parameter containing: [torch.float32 of size 256x256 (GPU 0)]
      (6): Parameter containing: [torch.float32 of size 256 (GPU 0)]
      (7): Parameter containing: [torch.float32 of size 320x256 (GPU 0)]
      (8): Parameter containing: [torch.float32 of size 320 (GPU 0)]
      (9): Parameter containing: [torch.float32 of size 256x8192 (GPU 0)]
      (10): Parameter containing: [torch.float32 of size 256 (GPU 0)]
      (11): Parameter containing: [torch.float32 of size 256x256 (GPU 0)]
      (12): Parameter containing: [torch.float32 of size 256 (GPU 0)]
      (13): Parameter conta

In [18]:
len_block = len(model.pipe.unet.up_blocks)
for i in range(len_block):
    print("Layer", i)
    len_resnet = len(model.pipe.unet.up_blocks[i].resnets)
    for j in range(len_resnet):
        gate_val = model.pipe.unet.up_blocks[i].resnets[j].light_block.gate
        print("Resnet", j, "gate", gate_val)

Layer 0
Resnet 0 gate Parameter containing:
tensor([0.0520], device='cuda:0', requires_grad=True)
Resnet 1 gate Parameter containing:
tensor([-0.0545], device='cuda:0', requires_grad=True)
Resnet 2 gate Parameter containing:
tensor([0.0718], device='cuda:0', requires_grad=True)
Layer 1
Resnet 0 gate Parameter containing:
tensor([0.1593], device='cuda:0', requires_grad=True)
Resnet 1 gate Parameter containing:
tensor([0.1727], device='cuda:0', requires_grad=True)
Resnet 2 gate Parameter containing:
tensor([-0.1518], device='cuda:0', requires_grad=True)
Layer 2
Resnet 0 gate Parameter containing:
tensor([-0.0840], device='cuda:0', requires_grad=True)
Resnet 1 gate Parameter containing:
tensor([-0.0484], device='cuda:0', requires_grad=True)
Resnet 2 gate Parameter containing:
tensor([0.0334], device='cuda:0', requires_grad=True)
Layer 3
Resnet 0 gate Parameter containing:
tensor([-0.0193], device='cuda:0', requires_grad=True)
Resnet 1 gate Parameter containing:
tensor([-0.0126], device='c

In [5]:
len_block = len(model.pipe.unet.down_blocks)
for i in range(len_block):
    print("Layer", i)
    len_resnet = len(model.pipe.unet.down_blocks[i].resnets)
    for j in range(len_resnet):
        gate_val = model.pipe.unet.down_blocks[i].resnets[j].light_block.gate
        print("Resnet", j, "gate", gate_val)

Layer 0
Resnet 0 gate Parameter containing:
tensor([-0.0034], device='cuda:0', requires_grad=True)
Resnet 1 gate Parameter containing:
tensor([-0.0030], device='cuda:0', requires_grad=True)
Layer 1
Resnet 0 gate Parameter containing:
tensor([-0.0042], device='cuda:0', requires_grad=True)
Resnet 1 gate Parameter containing:
tensor([0.0037], device='cuda:0', requires_grad=True)
Layer 2
Resnet 0 gate Parameter containing:
tensor([0.0057], device='cuda:0', requires_grad=True)
Resnet 1 gate Parameter containing:
tensor([-0.0069], device='cuda:0', requires_grad=True)
Layer 3
Resnet 0 gate Parameter containing:
tensor([0.0074], device='cuda:0', requires_grad=True)
Resnet 1 gate Parameter containing:
tensor([-0.0060], device='cuda:0', requires_grad=True)


In [4]:
model.pipe.unet.up_blocks[0].resnets[0].light_block.gate

Parameter containing:
tensor([0.], device='cuda:0', requires_grad=True)